(* generated by imandra-extract from "/Users/dave/dev/ai/verified-react/examples/simple/Counter.ire" *)

open Imandra_prelude;;

(* start generated code here *)

#1 "/Users/dave/dev/ai/verified-react/examples/simple/Counter.ire"
type msg =
                                                                    |
                                                                    Increment
                                                                    
                                                                    |
                                                                    Decrement 
#5 "/Users/dave/dev/ai/verified-react/examples/simple/Counter.ire"
type model =
                                                                    {
                                                                    count:
                                                                    int }
#7 "/Users/dave/dev/ai/verified-react/examples/simple/Counter.ire"
let update
                                                                    model msg
                                                                    =
                                                                    match msg
                                                                    with
                                                                    | 
                                                                    Increment
                                                                    ->
                                                                    {
                                                                    count =
                                                                    (model.count
                                                                    +
                                                                    (Z.of_string
                                                                    "1"))
                                                                    }
                                                                    | 
                                                                    Decrement
                                                                    ->
                                                                    {
                                                                    count =
                                                                    (model.count
                                                                    -
                                                                    (Z.of_string
                                                                    "1"))
                                                                    }
#13 "/Users/dave/dev/ai/verified-react/examples/simple/Counter.ire"
let goal_increment
                                                                    model =
                                                                    let new_model
                                                                    =
                                                                    update
                                                                    model
                                                                    Increment in
                                                                    new_model.count
                                                                    =
                                                                    (model.count
                                                                    +
                                                                    (Z.of_string
                                                                    "1"))
#18 "/Users/dave/dev/ai/verified-react/examples/simple/Counter.ire"
let goal_decrement
                                                                    model =
                                                                    let new_model
                                                                    =
                                                                    update
                                                                    model
                                                                    Decrement in
                                                                    new_model.count
                                                                    =
                                                                    (model.count
                                                                    -
                                                                    (Z.of_string
                                                                    "1"))

